// DPM — Catálogo Mestre Canónico v3
// O catálogoMaster é a única fonte de verdade. Legacy só é usado para a primeira migração.
import { getFirestore, doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const DATA_DOC="dpm_epi_data_v1",FAMILIES=["EPI","Equipamento","Ambiente","Portes"];
const normalize=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim().toUpperCase();
const stableId=(family,name)=>`${String(family).toLowerCase()}_${normalize(name).replace(/[^A-Z0-9]+/g,"-").replace(/^-|-$/g,"").toLowerCase()}`;
export function catalogRef(db){return doc(db,"appdata",DATA_DOC)}
export function articleId(article,family="EPI"){return String(article?.id||stableId(family,article?.nome||article?.name))}
export function normalizeArticle(article,family="EPI"){const nome=String(article?.nome||article?.name||"").trim();return {...article,id:articleId({...article,nome},family),nome,familia:family,ativo:article?.ativo!==false}}
function dedupe(list,f){const out=[],seenId=new Set(),seenName=new Set();for(const a of (list||[])){const x=normalizeArticle(a,f);if(!x.nome)continue;const id=articleId(x,f),name=normalize(x.nome);if(seenId.has(id)||seenName.has(name))continue;seenId.add(id);seenName.add(name);out.push(x)}return out}
function empty(){return Object.fromEntries(FAMILIES.map(f=>[f,[]]))}
export async function loadCatalog(db){
 const snap=await getDoc(catalogRef(db));const data=snap.exists()?(snap.data()||{}):{};
 const top=data.catalogMaster?.families||null,nested=data.budget?.inventoryCatalog?.families||null;
 let families=empty();
 if(top&&Object.keys(top).length){for(const f of FAMILIES)families[f]=dedupe(top[f],f)}
 else if(nested&&Object.keys(nested).length){for(const f of FAMILIES)families[f]=dedupe(nested[f],f)}
 else {const legacy=Array.isArray(data.matriz)?data.matriz.map(x=>({nome:x?.nome||x?.name,preco:x?.preco,riscos:x?.riscos,meses:x?.meses})).filter(x=>x.nome):[];families.EPI=dedupe(legacy,"EPI")}
 return {...data,budget:{...(data.budget||{}),inventoryCatalog:{...(data.budget?.inventoryCatalog||{}),version:3,canonical:true,families}},catalogMaster:{version:3,canonical:true,families}}
}
export async function saveCatalog(db,data){const families=data?.catalogMaster?.families||data?.budget?.inventoryCatalog?.families||empty();await setDoc(catalogRef(db),{catalogMaster:{version:3,canonical:true,families},budget:{inventoryCatalog:{version:3,canonical:true,families}}},{merge:true})}
export function getArticles(data,family="EPI",includeInactive=true){const list=data?.catalogMaster?.families?.[family]||data?.budget?.inventoryCatalog?.families?.[family]||[];return includeInactive?list:list.filter(x=>x.ativo!==false)}
export function findArticle(data,name,family="EPI"){const wanted=normalize(name);return getArticles(data,family).find(x=>normalize(x.nome)===wanted||articleId(x,family)===String(name))}
export function addArticle(data,article,family="EPI"){const normalized=normalizeArticle(article,family);data.catalogMaster||={families:empty()};data.catalogMaster.families||=empty();data.catalogMaster.families[family]||=[];if(data.catalogMaster.families[family].some(x=>normalize(x.nome)===normalize(normalized.nome)))throw new Error("Artigo já existe no Catálogo Mestre.");data.catalogMaster.families[family].push(normalized);data.budget||={};data.budget.inventoryCatalog||={};data.budget.inventoryCatalog.families=data.catalogMaster.families;return normalized}
export function setArticleActive(data,id,active,family="EPI"){const list=getArticles(data,family);const item=list.find(x=>articleId(x,family)===String(id));if(!item)throw new Error("Artigo não encontrado no Catálogo Mestre.");item.ativo=Boolean(active);data.catalogMaster.families[family]=list;data.budget.inventoryCatalog.families=data.catalogMaster.families;return item}
export function canHardDelete(data,id,family="EPI"){const item=getArticles(data,family).find(x=>articleId(x,family)===String(id));if(!item)return{ok:false,reason:"Artigo não encontrado."};const name=normalize(item.nome);const stock=Object.values(data.stocks||{}).reduce((sum,warehouse)=>{const value=Object.entries(warehouse||{}).find(([k])=>normalize(k)===name)?.[1];if(typeof value==="number")return sum+Math.max(0,value);return sum+Math.max(0,Number(value?.loose||0))+Object.values(value?.sizes||{}).reduce((s,n)=>s+Math.max(0,Number(n)||0),0)},0);const events=Array.isArray(data.eventos)?data.eventos.filter(e=>normalize(e?.epi)===name).length:0;return stock===0&&events===0?{ok:true}:{ok:false,reason:`O artigo tem stock (${stock}) ou histórico (${events} eventos).`}}
export function hardDeleteArticle(data,id,family="EPI"){const check=canHardDelete(data,id,family);if(!check.ok)throw new Error(check.reason);const item=getArticles(data,family).find(x=>articleId(x,family)===String(id));const name=normalize(item.nome);data.catalogMaster.families[family]=getArticles(data,family).filter(x=>articleId(x,family)!==String(id));data.budget.inventoryCatalog.families=data.catalogMaster.families;if(family==="EPI"){data.matriz=(data.matriz||[]).filter(x=>normalize(x?.nome||x?.name)!==name);if(data.epiModels){Object.keys(data.epiModels).forEach(k=>{if(normalize(k)===name)delete data.epiModels[k]})}data.budget.management||={};data.budget.management.planning=Object.fromEntries(Object.entries(data.budget.management.planning||{}).filter(([key])=>normalize(key)!==name))}return item}
window.DPMCatalogMaster={articleId,normalizeArticle,loadCatalog,saveCatalog,getArticles,findArticle,addArticle,setArticleActive,canHardDelete,hardDeleteArticle};