// DPM — Entrega final de EPI: artigo + modelo + tamanho + stock + assinatura
import { getApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const DOC="dpm_epi_data_v1", DELIVERIES="deliveries";
const db=()=>getFirestore(getApp()), ref=()=>doc(db(),"appdata",DOC);
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/\s+/g," ").trim();
const money=v=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const addMonths=(date,months)=>{const d=new Date(date);d.setMonth(d.getMonth()+Number(months||0));return d.toISOString().slice(0,10)};
let data=null, pad=null;
function ensure(d){d=d||{};d.matriz=Array.isArray(d.matriz)?d.matriz:[];d.trabalhadores=Array.isArray(d.trabalhadores)?d.trabalhadores:[];d.eventos=Array.isArray(d.eventos)?d.eventos:[];d.stocks ||= {};d.warehouses=Array.isArray(d.warehouses)?d.warehouses:[];d.epiModels ||= {};d.warehouses.forEach(w=>{d.stocks[w] ||= {};d.matriz.forEach(e=>{d.stocks[w][e.nome] ||= {loose:0,sizes:{}};if(typeof d.stocks[w][e.nome]==="number")d.stocks[w][e.nome]={loose:d.stocks[w][e.nome],sizes:{}};d.stocks[w][e.nome].sizes ||= {};d.stocks[w][e.nome].models ||= {}})});return d}
async function load(){const s=await getDoc(ref());data=ensure(s.exists()?s.data():{});return data}
function models(epi){return Array.isArray(data.epiModels?.[epi])?data.epiModels[epi].filter(m=>m&&m.ativo!==false):[]}
function stockRec(w,epi){data.stocks[w] ||= {};let r=data.stocks[w][epi];if(typeof r==="number")r={loose:r,sizes:{}};if(!r||typeof r!=="object")r={loose:0,sizes:{}};r.loose=Number(r.loose||r.semTamanho||0);r.sizes ||= {};r.models ||= {};data.stocks[w][epi]=r;return r}
function modelRec(w,epi,name){const r=stockRec(w,epi);r.models[name] ||= {loose:0,sizes:{}};r.models[name].loose=Number(r.models[name].loose||0);r.models[name].sizes ||= {};return r.models[name]}
function sizesFor(w,epi,model){const r=model?modelRec(w,epi,model.nome):stockRec(w,epi);const configured=model?.tamanhos||[];const existing=Object.keys(r.sizes||{});return [...new Set([...configured,...existing].map(x=>String(x).trim().toUpperCase()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-PT",{numeric:true}))}
function available(w,epi,modelName,size){const r=modelName?modelRec(w,epi,modelName):stockRec(w,epi);const k=String(size||"").trim().toUpperCase();return k?Number(r.sizes[k]||0):Number(r.loose||0)}
function remove(w,epi,modelName,qty,size){const r=modelName?modelRec(w,epi,modelName):stockRec(w,epi);const k=String(size||"").trim().toUpperCase();if(k)r.sizes[k]=Math.max(0,Number(r.sizes[k]||0)-Number(qty||0));else r.loose=Math.max(0,Number(r.loose||0)-Number(qty||0))}
function responsible(){return document.querySelector('.user-chip span:last-child')?.textContent?.trim()||'SuperAdmin'}
function workerFromPage(){const name=document.querySelector('.detail-header h1')?.textContent?.trim()||'';return data.trabalhadores.find(w=>norm(w.nome)===norm(name))}
function item(name){const epi=data.matriz.find(e=>e.nome===name)||data.matriz[0];const ms=models(epi.nome);return `<div class="delivery-item df-item"><div class="field-row"><select class="select" name="epi">${data.matriz.map(e=>`<option value="${esc(e.nome)}" ${e.nome===epi.nome?'selected':''}>${esc(e.nome)}</option>`).join('')}</select></div><div class="field-row"><select class="select" name="model" ${ms.length?'':'disabled'}>${ms.length?`<option value="">Selecionar modelo</option>${ms.map(m=>`<option value="${esc(m.id)}">${esc(m.nome)}${m.preco?` · ${money(m.preco)}`:''}</option>`).join('')}`:`<option value="">Sem modelo configurado</option>`}</select></div><div class="field-row two"><select class="select" name="size"><option value="">Sem tamanho</option></select><input class="input" name="qty" type="number" min="1" value="1" required></div><div class="field-row"><input class="input" name="months" type="number" min="1" value="${epi.meses||12}" required></div><div class="info-box df-info"></div><div style="display:flex;justify-content:flex-end"><button class="ghost-btn" type="button" data-df-remove>Remover</button></div></div>`}
function refresh(el,warehouse){const epi=data.matriz.find(e=>e.nome===el.querySelector('[name="epi"]').value)||data.matriz[0],sel=el.querySelector('[name="model"]'),ms=models(epi.nome),oldModel=sel?.value||'',size=el.querySelector('[name="size"]'),oldSize=size.value;if(sel){sel.disabled=!ms.length;sel.innerHTML=ms.length?`<option value="">Selecionar modelo</option>${ms.map(x=>`<option value="${esc(x.id)}" ${x.id===oldModel?'selected':''}>${esc(x.nome)}${x.preco?` · ${money(x.preco)}`:''}</option>`).join('')}`:`<option value="">Sem modelo configurado</option>`}const chosen=ms.find(x=>x.id===sel?.value);size.innerHTML='<option value="">Sem tamanho</option>'+sizesFor(warehouse,epi.nome,chosen).map(s=>`<option value="${esc(s)}" ${s===oldSize?'selected':''}>${esc(s)} (${available(warehouse,epi.nome,chosen?.nome||'',s)})</option>`).join('');el.querySelector('.df-info').textContent=`Riscos: ${epi.riscos||'—'} · ${chosen?`Modelo: ${chosen.nome} · ${money(chosen.preco||0)}`:'Sem modelo'} · Validade: ${epi.meses||12} meses`}
async function openDelivery(){try{await load();const w=workerFromPage();if(!w)throw new Error('Não foi possível identificar o trabalhador selecionado.');const root=document.getElementById('modal-root');if(!root)throw new Error('Janela de entrega indisponível.');root.innerHTML=`<div class="modal-overlay" data-df-close><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>Registar Entrega de EPI</h2><p class="meta">${esc(w.nome)} · ${esc(w.delegacao)}</p></div><button class="icon-btn" type="button" data-df-close>×</button></div><form data-df-form data-worker="${w.id}" data-warehouse="${esc(w.delegacao)}"><div id="df-items">${item(data.matriz[0]?.nome||'')}</div><button type="button" class="ghost-btn" data-df-add>+ EPI</button><div style="display:flex;justify-content:flex-end;margin-top:14px"><button type="submit" class="primary-btn">Continuar → Assinatura</button></div></form></div></div>`;root.querySelectorAll('.df-item').forEach(x=>refresh(x,w.delegacao));root.querySelectorAll('[data-df-close]').forEach(x=>x.onclick=()=>root.innerHTML='')}catch(e){console.error('DPM entrega',e);alert(`Não foi possível abrir a entrega.\n\n${e.message||e}`)}}
function collect(form){const w=data.trabalhadores.find(x=>String(x.id)===String(form.dataset.worker)),items=[...form.querySelectorAll('.df-item')].map(el=>{const epi=data.matriz.find(e=>e.nome===el.querySelector('[name="epi"]').value),m=models(epi?.nome).find(x=>x.id===el.querySelector('[name="model"]').value),qty=Number(el.querySelector('[name="qty"]').value||0),months=Number(el.querySelector('[name="months"]').value||epi?.meses||12),size=el.querySelector('[name="size"]').value;return{epi,model:m||null,qty,months,size,validity:addMonths(new Date(),months)}}).filter(x=>x.epi&&x.qty>0);if(!w)throw new Error('Trabalhador não encontrado.');if(!items.length)throw new Error('Adicione pelo menos uma entrega.');if(items.some(x=>models(x.epi.nome).length&&!x.model))throw new Error('Selecione o modelo de todos os EPI que têm modelos configurados.');if(items.some(x=>available(w.delegacao,x.epi.nome,x.model?.nome||'',x.size)<x.qty))throw new Error('Não existe stock suficiente para uma ou mais linhas.');return{worker:w,items,warehouse:w.delegacao,responsavel:responsible()}}
function newPad(canvas){const ratio=Math.max(devicePixelRatio||1,1),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*ratio));canvas.height=Math.max(1,Math.floor(r.height*ratio));const c=canvas.getContext('2d');c.scale(ratio,ratio);c.strokeStyle='#ffc35a';c.lineWidth=3;c.lineCap='round';c.lineJoin='round';let strokes=[],drawing=false,cur=null;const p=e=>{const b=canvas.getBoundingClientRect();return{x:e.clientX-b.left,y:e.clientY-b.top}};canvas.onpointerdown=e=>{drawing=true;cur={points:[]};strokes.push(cur);const q=p(e);cur.points.push(q);c.beginPath();c.moveTo(q.x,q.y);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(!drawing)return;e.preventDefault();const q=p(e);cur.points.push(q);c.lineTo(q.x,q.y);c.stroke()};canvas.onpointerup=canvas.onpointerleave=canvas.onpointercancel=()=>{drawing=false;cur=null};return{strokes,clear:()=>{strokes.length=0;c.clearRect(0,0,canvas.width,canvas.height)}}}
function signature(payload,phase){const root=document.getElementById('modal-root'),summary=payload.items.map(i=>`${esc(i.epi.nome)}${i.model?` · ${esc(i.model.nome)}`:''}${i.size?` · ${esc(i.size)}`:''} · ${i.qty}`).join('<br>');root.innerHTML=`<section class="kiosk"><header><div><h1>${phase==='worker'?'Assinatura do Trabalhador':'Rubrica de Quem Entrega'}</h1><p class="meta">${esc(payload.worker.nome)}<br>${summary}</p></div><button type="button" class="ghost-btn" data-df-cancel>Cancelar</button></header><div><p class="legal">${phase==='worker'?'Declaro ter recebido os EPIs indicados, em bom estado, comprometendo-me a utilizá-los corretamente.':'Confirmo a entrega dos EPIs ao trabalhador.'}</p><label class="signature-label">Assine abaixo</label><canvas class="signature-pad" id="df-sign"></canvas></div><div class="kiosk-actions"><button class="ghost-btn" type="button" data-df-clear>Limpar</button><button class="ghost-btn" type="button" data-df-nosign>Sem assinatura</button><button class="primary-btn" type="button" data-df-next>${phase==='worker'?'Confirmar assinatura →':'Confirmar e Guardar'}</button></div></section>`;pad=newPad(document.getElementById('df-sign'));root.querySelector('[data-df-clear]').onclick=()=>pad.clear();root.querySelector('[data-df-cancel]').onclick=()=>root.innerHTML='';root.querySelector('[data-df-nosign]').onclick=()=>{if(phase==='worker'){payload.workerSig=null;payload.noSign=true;signature(payload,'deliverer')}else{payload.delivererSig=null;payload.noSign=true;save(payload)}};root.querySelector('[data-df-next]').onclick=()=>{if(!pad.strokes.length&&!confirm('A assinatura está vazia. Avançar?'))return;if(phase==='worker'){payload.workerSig=pad.strokes;signature(payload,'deliverer')}else{payload.delivererSig=pad.strokes;save(payload)}}}
async function save(payload){const batch=`DEL-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;try{await Promise.all(payload.items.map(i=>addDoc(collection(db(),DELIVERIES),{batch_id:batch,worker_id:payload.worker.id,worker_nome:payload.worker.nome,epi_type:i.epi.nome,model_id:i.model?.id||'',model_name:i.model?.nome||'',qtd:i.qty,tamanho:String(i.size||'').toUpperCase(),delivery_date:today(),validity_date:i.validity,riscos:i.epi.riscos||'',unit_price:Number(i.model?.preco??i.epi.preco??0),total_cost:Number(i.qty)*Number(i.model?.preco??i.epi.preco??0),responsavel:payload.responsavel,sem_assinatura:!!payload.noSign,signature_points_trabalhador:payload.workerSig||null,signature_points_entregador:payload.delivererSig||null,created_at:Date.now()})));for(const i of payload.items){data.eventos.forEach(e=>{if(e.tipo==='ENTREGA'&&e.idTrab===payload.worker.id&&e.statusAlerta==='ATIVO'&&norm(e.epi)===norm(i.epi.nome)&&norm(e.modelo||'')===norm(i.model?.nome||'')){e.statusAlerta='BAIXA';e.estado='Baixa por nova entrega'}});remove(payload.warehouse,i.epi.nome,i.model?.nome||'',i.qty,i.size);data.eventos.push({id:`EVT-${Date.now()}-${Math.random().toString(16).slice(2,8)}`,idTrab:payload.worker.id,data:new Date().toLocaleDateString('pt-PT'),tipo:'ENTREGA',epi:i.epi.nome,modelo:i.model?.nome||'',modelo_id:i.model?.id||'',preco_unitario:Number(i.model?.preco??i.epi.preco??0),custo:Number(i.qty)*Number(i.model?.preco??i.epi.preco??0),qtd:i.qty,tamanho:String(i.size||'').toUpperCase(),armazem:payload.warehouse,estado:'Entregue',statusAlerta:'ATIVO',validade:i.validity,responsavel:payload.responsavel,assinado:!payload.noSign})}await setDoc(ref(),{stocks:data.stocks,eventos:data.eventos},{merge:true});document.getElementById('modal-root').innerHTML='';alert('Entrega guardada com modelo, tamanho, stock e custo.')}catch(e){console.error(e);alert(`Não foi possível guardar a entrega.\n\n${e.message||e}`)}}
function start(){document.addEventListener('click',e=>{const delivery=e.target.closest('[data-modal="delivery"]');if(delivery){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openDelivery();return}if(e.target.closest('[data-df-close]')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();document.getElementById('modal-root').innerHTML='';return}if(e.target.closest('[data-df-add]')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const f=document.querySelector('[data-df-form]');const holder=f?.querySelector('#df-items');if(f&&holder){holder.insertAdjacentHTML('beforeend',item(''));refresh(holder.lastElementChild,f.dataset.warehouse)}return}if(e.target.closest('[data-df-remove]')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const rows=document.querySelectorAll('.df-item');if(rows.length>1)e.target.closest('.df-item')?.remove();return}},true);document.addEventListener('change',e=>{const f=e.target.closest('[data-df-form]');if(!f)return;const row=e.target.closest('.df-item');if(row&&(e.target.name==='epi'||e.target.name==='model'))refresh(row,f.dataset.warehouse)},true);document.addEventListener('submit',e=>{const f=e.target.closest('[data-df-form]');if(!f)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{signature(collect(f),'worker')}catch(err){alert(err.message||err)}},true)}
start();
