// DPM — Entrega Core V2
// A janela é aberta antes dos handlers globais do app e, depois de aberta,
// trata os seus eventos no próprio modal-root. Não usa MutationObserver nem
// listeners globais para campos internos da entrega.
import { getApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const DOC="dpm_epi_data_v1", DELIVERIES="deliveries";
const db=()=>getFirestore(getApp()), ref=()=>doc(db(),"appdata",DOC);
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/\s+/g," ").trim();
const money=v=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const addMonths=(date,months)=>{const d=new Date(date);d.setMonth(d.getMonth()+Number(months||0));return d.toISOString().slice(0,10)};
let state=null, signaturePoints=null;

function prepare(d){d=d||{};d.matriz=Array.isArray(d.matriz)?d.matriz:[];d.trabalhadores=Array.isArray(d.trabalhadores)?d.trabalhadores:[];d.eventos=Array.isArray(d.eventos)?d.eventos:[];d.stocks=d.stocks||{};d.warehouses=Array.isArray(d.warehouses)?d.warehouses:[];d.epiModels=d.epiModels||{};d.warehouses.forEach(w=>{d.stocks[w]=d.stocks[w]||{};d.matriz.forEach(e=>{const r=d.stocks[w][e.nome];if(typeof r==='number')d.stocks[w][e.nome]={loose:r,sizes:{},models:{}};else if(!r||typeof r!=='object')d.stocks[w][e.nome]={loose:0,sizes:{},models:{}};d.stocks[w][e.nome].sizes=d.stocks[w][e.nome].sizes||{};d.stocks[w][e.nome].models=d.stocks[w][e.nome].models||{}})});return d}
async function load(){const s=await getDoc(ref());state=prepare(s.exists()?s.data():{});return state}
function models(epi){return Array.isArray(state?.epiModels?.[epi])?state.epiModels[epi].filter(m=>m&&m.ativo!==false):[]}
function stock(warehouse,epi,model){state.stocks[warehouse]=state.stocks[warehouse]||{};let r=state.stocks[warehouse][epi];if(typeof r==='number')r={loose:r,sizes:{},models:{}};if(!r||typeof r!=='object')r={loose:0,sizes:{},models:{}};r.loose=Number(r.loose||r.semTamanho||0);r.sizes=r.sizes||{};r.models=r.models||{};if(model){r.models[model]=r.models[model]||{loose:0,sizes:{}};r.models[model].loose=Number(r.models[model].loose||0);r.models[model].sizes=r.models[model].sizes||{};return r.models[model]}state.stocks[warehouse][epi]=r;return r}
function sizes(warehouse,epi,model){const r=stock(warehouse,epi,model?.nome);const configured=model?.tamanhos||[];const existing=Object.keys(r.sizes||{});return [...new Set([...configured,...existing].map(x=>String(x).trim().toUpperCase()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-PT',{numeric:true}))}
function available(warehouse,epi,model,size){const r=stock(warehouse,epi,model||undefined);const k=String(size||'').trim().toUpperCase();return k?Number(r.sizes[k]||0):Number(r.loose||0)}
function worker(){const n=document.querySelector('.detail-header h1')?.textContent?.trim()||'';return state.trabalhadores.find(w=>norm(w.nome)===norm(n))}
function row(epiName){const epi=state.matriz.find(e=>e.nome===epiName)||state.matriz[0];return `<div class="delivery-item df2-item"><div class="field-row"><label>Artigo</label><select class="select" data-df2="epi">${state.matriz.map(e=>`<option value="${esc(e.nome)}" ${e.nome===epi?.nome?'selected':''}>${esc(e.nome)}</option>`).join('')}</select></div><div class="field-row"><label>Modelo</label><select class="select" data-df2="model"></select></div><div class="field-row two"><div><label>Tamanho</label><select class="select" data-df2="size"><option value="">Sem tamanho</option></select></div><div><label>Quantidade</label><input class="input" data-df2="qty" type="number" min="1" step="1" value="1"></div></div><div class="field-row"><label>Validade (meses)</label><input class="input" data-df2="months" type="number" min="1" value="${Number(epi?.meses||12)}"></div><div class="info-box" data-df2="info"></div><div style="display:flex;justify-content:flex-end"><button class="ghost-btn" type="button" data-df2="remove">Remover</button></div></div>`}
function refresh(r,warehouse){const epiName=r.querySelector('[data-df2="epi"]')?.value||'';const epi=state.matriz.find(e=>e.nome===epiName)||state.matriz[0];const ms=models(epi?.nome);const msel=r.querySelector('[data-df2="model"]');const old=msel.value;msel.innerHTML=ms.length?'<option value="">Selecionar modelo</option>'+ms.map(m=>`<option value="${esc(m.id)}">${esc(m.nome)}${m.preco?` · ${money(m.preco)}`:''}</option>`).join(''):'<option value="">Sem modelo configurado</option>';msel.disabled=!ms.length;if(ms.some(m=>m.id===old))msel.value=old;const chosen=ms.find(m=>m.id===msel.value);const s=r.querySelector('[data-df2="size"]');const oldSize=s.value;s.innerHTML='<option value="">Sem tamanho</option>'+sizes(warehouse,epi.nome,chosen).map(x=>`<option value="${esc(x)}">${esc(x)} (${available(warehouse,epi.nome,chosen?.nome||'',x)})</option>`).join('');if([...s.options].some(o=>o.value===oldSize))s.value=oldSize;r.querySelector('[data-df2="info"]').textContent=`${chosen?`Modelo: ${chosen.nome} · ${money(chosen.preco||0)}`:'Selecione um modelo'} · Stock por tamanho`;}
function open(){(async()=>{try{await load();const w=worker();if(!w)throw new Error('Não foi possível identificar o trabalhador.');const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-overlay"><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>Registar Entrega de EPI</h2><p class="meta">${esc(w.nome)} · ${esc(w.delegacao)}</p></div><button type="button" class="icon-btn" data-df2="close">×</button></div><form id="df2-form" data-worker="${esc(w.id)}" data-warehouse="${esc(w.delegacao)}"><div id="df2-items">${row(state.matriz[0]?.nome||'')}</div><button type="button" class="ghost-btn" data-df2="add">+ EPI</button><div style="display:flex;justify-content:flex-end;margin-top:14px"><button type="submit" class="primary-btn">Continuar → Assinatura</button></div></form></div></div>`;root.querySelectorAll('.df2-item').forEach(x=>refresh(x,w.delegacao));}catch(e){console.error('[DPM delivery]',e);alert('Não foi possível abrir a entrega.\n\n'+(e.message||e));}})()}
function collect(form){const w=state.trabalhadores.find(x=>String(x.id)===String(form.dataset.worker));if(!w)throw new Error('Trabalhador não encontrado.');const items=[...form.querySelectorAll('.df2-item')].map(r=>{const epi=state.matriz.find(e=>e.nome===r.querySelector('[data-df2="epi"]').value);const m=models(epi?.nome).find(x=>x.id===r.querySelector('[data-df2="model"]').value)||null;const size=r.querySelector('[data-df2="size"]').value;const qty=Number(r.querySelector('[data-df2="qty"]').value||0);const months=Number(r.querySelector('[data-df2="months"]').value||epi?.meses||12);return{epi,model:m,size,qty,validity:addMonths(new Date(),months)}}).filter(x=>x.epi&&x.qty>0);if(!items.length)throw new Error('Adicione pelo menos uma entrega.');for(const i of items){if(models(i.epi.nome).length&&!i.model)throw new Error(`Selecione o modelo de ${i.epi.nome}.`);if(i.size&&available(w.delegacao,i.epi.nome,i.model?.nome||'',i.size)<i.qty)throw new Error(`Stock insuficiente: ${i.epi.nome} ${i.size}.`);}return{worker:w,warehouse:w.delegacao,items,responsavel:document.querySelector('.user-chip span:last-child')?.textContent?.trim()||'SuperAdmin'};}
function signature(payload,phase){const root=document.getElementById('modal-root');const summary=payload.items.map(i=>`${esc(i.epi.nome)}${i.model?' · '+esc(i.model.nome):''}${i.size?' · '+esc(i.size):''} · ${i.qty}`).join('<br>');root.innerHTML=`<section class="kiosk"><header><div><h1>${phase==='worker'?'Assinatura do Trabalhador':'Rubrica de Quem Entrega'}</h1><p class="meta">${esc(payload.worker.nome)}<br>${summary}</p></div><button type="button" class="ghost-btn" data-df2="cancel">Cancelar</button></header><div><p class="legal">${phase==='worker'?'Declaro ter recebido os EPIs indicados, em bom estado, comprometendo-me a utilizá-los corretamente.':'Confirmo a entrega dos EPIs ao trabalhador.'}</p><label class="signature-label">Assine abaixo</label><canvas class="signature-pad" id="df2-sign"></canvas></div><div class="kiosk-actions"><button class="ghost-btn" type="button" data-df2="clear">Limpar</button><button class="ghost-btn" type="button" data-df2="nosign">Sem assinatura</button><button class="primary-btn" type="button" data-df2="next">${phase==='worker'?'Confirmar assinatura →':'Confirmar e Guardar'}</button></div></section>`;const c=root.querySelector('#df2-sign'),ctx=c.getContext('2d'),ratio=Math.max(devicePixelRatio||1,1),box=c.getBoundingClientRect();c.width=Math.max(1,box.width*ratio);c.height=Math.max(1,box.height*ratio);ctx.scale(ratio,ratio);ctx.strokeStyle='#ffc35a';ctx.lineWidth=3;ctx.lineCap='round';let drawing=false;signaturePoints=[];c.addEventListener('pointerdown',e=>{drawing=true;const b=c.getBoundingClientRect();signaturePoints.push([{x:e.clientX-b.left,y:e.clientY-b.top}]);c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drawing)return;const b=c.getBoundingClientRect(),p={x:e.clientX-b.left,y:e.clientY-b.top};let s=signaturePoints.at(-1);const last=s.at(-1);s.push(p);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke()});c.addEventListener('pointerup',()=>drawing=false);root.querySelector('[data-df2="clear"]').onclick=()=>{signaturePoints=[];ctx.clearRect(0,0,c.width,c.height)};root.querySelector('[data-df2="cancel"]').onclick=()=>root.innerHTML='';root.querySelector('[data-df2="nosign"]').onclick=()=>phase==='worker'?signature({...payload,workerSig:null,noSign:true},'deliverer'):save({...payload,delivererSig:null,noSign:true});root.querySelector('[data-df2="next"]').onclick=()=>{if(!signaturePoints.length&&!confirm('A assinatura está vazia. Avançar?'))return;phase==='worker'?signature({...payload,workerSig:signaturePoints},'deliverer'):save({...payload,delivererSig:signaturePoints})}}
async function save(p){try{const batch=`DEL-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;await Promise.all(p.items.map(i=>addDoc(collection(db(),DELIVERIES),{batch_id:batch,worker_id:p.worker.id,worker_nome:p.worker.nome,epi_type:i.epi.nome,model_id:i.model?.id||'',model_name:i.model?.nome||'',qtd:i.qty,tamanho:String(i.size||'').toUpperCase(),delivery_date:today(),validity_date:i.validity,unit_price:Number(i.model?.preco??i.epi.preco??0),total_cost:Number(i.qty)*Number(i.model?.preco??i.epi.preco??0),responsavel:p.responsavel,sem_assinatura:!!p.noSign,signature_points_trabalhador:p.workerSig||null,signature_points_entregador:p.delivererSig||null,created_at:Date.now()})));for(const i of p.items){const r=stock(p.warehouse,i.epi.nome,i.model?.nome||'');if(i.size){const k=i.size.toUpperCase();r.sizes[k]=Math.max(0,Number(r.sizes[k]||0)-i.qty)}else r.loose=Math.max(0,Number(r.loose||0)-i.qty);p.state=state.eventos.push({id:`EVT-${Date.now()}-${Math.random().toString(16).slice(2,8)}`,idTrab:p.worker.id,tipo:'ENTREGA',epi:i.epi.nome,modelo:i.model?.nome||'',modelo_id:i.model?.id||'',qtd:i.qty,tamanho:String(i.size||'').toUpperCase(),armazem:p.warehouse,estado:'Entregue',statusAlerta:'ATIVO',validade:i.validity,responsavel:p.responsavel,assinado:!p.noSign})}await setDoc(ref(),{stocks:state.stocks,eventos:state.eventos},{merge:true});document.getElementById('modal-root').innerHTML='';alert('Entrega guardada com sucesso.')}catch(e){console.error('[DPM delivery save]',e);alert('Não foi possível guardar a entrega.\n\n'+(e.message||e))}}
function boot(){document.addEventListener('click',e=>{const launch=e.target.closest('[data-modal="delivery"]');if(launch){e.preventDefault();e.stopImmediatePropagation();open();}},true);const root=document.getElementById('modal-root');root.addEventListener('click',e=>{const a=e.target.closest('[data-df2]');if(!a)return;const action=a.dataset.df2;if(action==='add'){e.preventDefault();root.querySelector('#df2-items').insertAdjacentHTML('beforeend',row(''));refresh(root.querySelector('#df2-items').lastElementChild,root.querySelector('#df2-form').dataset.warehouse)}else if(action==='remove'){e.preventDefault();const rs=root.querySelectorAll('.df2-item');if(rs.length>1)a.closest('.df2-item').remove()}else if(action==='close'||action==='cancel'){e.preventDefault();root.innerHTML=''}},false);root.addEventListener('change',e=>{const r=e.target.closest('.df2-item'),f=e.target.closest('#df2-form');if(!r||!f)return;if(e.target.dataset.df2==='epi'||e.target.dataset.df2==='model')refresh(r,f.dataset.warehouse)},false);root.addEventListener('submit',e=>{if(!e.target.matches('#df2-form'))return;e.preventDefault();e.stopPropagation();try{signature(collect(e.target),'worker')}catch(err){alert(err.message||err)}},false)}
boot();