// DPM — carregador seguro do Inventário Mestre
// Captura a ação no nível WINDOW antes dos handlers globais da app.
let loading=false, loaded=false;
function ensureRoot(){let r=document.getElementById('modal-root');if(r)return r;r=document.createElement('div');r.id='modal-root';document.body.appendChild(r);return r}
async function openInventory(){if(loading)return;loading=true;try{ensureRoot();if(!loaded){await import('./inventory-general-v4.js?v=20260814-inventory-fix4');loaded=true}if(typeof window.DPMInventoryGeneral?.open!=='function')throw new Error('O módulo do Inventário Mestre não disponibilizou a abertura.');await window.DPMInventoryGeneral.open()}catch(e){console.error('Inventário Mestre:',e);alert(`Não foi possível abrir o Inventário Mestre.\n\n${e?.message||e}`)}finally{loading=false}}
function targetFor(t){if(!t?.closest)return null;return t.closest('[data-inventory-general],[data-safe-inventory-button],[data-open-inventory-master]')||t.closest('button,a')?.textContent?.match(/inventário mestre/i)?t.closest('button,a'):null}
window.addEventListener('click',e=>{const target=targetFor(e.target);if(!target)return;e.preventDefault();e.stopImmediatePropagation();openInventory()},true);
function bindExisting(){document.querySelectorAll('[data-inventory-general],[data-safe-inventory-button],[data-open-inventory-master]').forEach(el=>{el.dataset.inventoryBound='1';if(el.tagName==='BUTTON')el.type='button'})}
function inject(){const title=document.querySelector('.screen-title h1')?.textContent?.trim();if(title!=='Armazém'||document.querySelector('[data-safe-inventory-button]'))return;const target=document.querySelector('main .section-head')||document.querySelector('.screen-title');if(!target)return;const button=document.createElement('button');button.type='button';button.className='ghost-btn';button.dataset.safeInventoryButton='1';button.textContent='▦ Inventário Mestre';target.prepend(button)}
new MutationObserver(()=>{bindExisting();inject()}).observe(document.body,{childList:true,subtree:true});setTimeout(()=>{bindExisting();inject()},300);window.DPMOpenInventoryMaster=openInventory;