import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, doc, runTransaction, getDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAqt5RDygjfeQZ3zq8dYhEGbyIjg00Bbks",authDomain:"dpm-epi.firebaseapp.com",projectId:"dpm-epi",storageBucket:"dpm-epi.firebasestorage.app",messagingSenderId:"1043253642340",appId:"1:1043253642340:web:d3e0920050b8407f48cb71",measurementId:"G-VZK3WE1MDJ"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),db=getFirestore(app),MAIN_DOC="dpm_epi_data_v1";
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const todayPT=()=>new Date().toLocaleDateString("pt-PT");
const currentWorkerName=()=>document.querySelector(".detail-header h1")?.textContent?.trim()||"";
function normalizeStock(v){if(typeof v==="number")return{loose:v,sizes:{}};if(!v||typeof v!=="object")return{loose:0,sizes:{}};return{loose:Number(v.loose||0),sizes:Object.fromEntries(Object.entries(v.sizes||{}).map(([k,n])=>[String(k).toUpperCase(),Number(n||0)]))};}
function addStock(data,warehouse,epi,size,qty){if(!data.stocks)data.stocks={};if(!data.stocks[warehouse])data.stocks[warehouse]={};const s=normalizeStock(data.stocks[warehouse][epi]),key=String(size||"").trim().toUpperCase();if(key)s.sizes[key]=Number(s.sizes[key]||0)+qty;else s.loose+=qty;data.stocks[warehouse][epi]=s;}
function installStyles(){if(document.getElementById("per-item-return-styles"))return;const s=document.createElement("style");s.id="per-item-return-styles";s.textContent=`
.epi-return-btn{font-size:0;padding:4px 6px;min-width:30px;min-height:28px;border-radius:7px;border:1px solid #c85a4b;background:#fff1ee;color:#a62f22;font-weight:800;line-height:1;cursor:pointer}.epi-return-btn::before{content:"↩";font-size:15px}.epi-return-btn:hover{background:#ffe0da;color:#8f2419}.epi-return-cell{width:40px;text-align:center;vertical-align:middle}
.return-confirm-box{padding:14px;border-radius:10px;background:var(--panel-2,#eef4f7);border:1px solid var(--line,#b8c7d0)}.return-confirm-box strong{display:block;margin-bottom:6px}.return-confirm-box .meta{display:block;line-height:1.45}
.months-help-text{display:block;margin-top:4px;font-size:.72rem;color:#52636f;line-height:1.3}.return-destination{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.return-destination button{min-height:42px}.return-destination .selected{outline:2px solid currentColor;outline-offset:1px}.return-stock{color:#145b3b!important;background:#e3f5ea!important;border:1px solid #a8d8bb!important}.return-discard{color:#8b1e31!important;background:#fde4e8!important;border:1px solid #e5a7b3!important}
@media(prefers-color-scheme:dark){.return-confirm-box{background:#1d3142;border-color:#526b79}.months-help-text{color:#b8cbd5}.return-stock{color:#bcefd2!important;background:#195a41!important;border-color:#3d8a67!important}.return-discard{color:#ffd3da!important;background:#6e2637!important;border-color:#a85a6b!important}}
`;document.head.appendChild(s);}
function improveMonthsField(){document.querySelectorAll('input[name="meses"]').forEach(input=>{if(input.dataset.monthsEnhanced==="1")return;input.dataset.monthsEnhanced="1";const wrap=input.closest(".field-row")||input.parentElement;if(!wrap)return;const old=wrap.querySelector(".field-label");if(old)old.textContent="Validade do EPI (meses)";const help=document.createElement("span");help.className="months-help-text";help.textContent="Período de validade após a entrega. Preenchido automaticamente de acordo com o EPI selecionado.";wrap.appendChild(help);input.setAttribute("aria-label","Validade do EPI em meses");});}
async function getActiveEvents(){const snap=await getDoc(doc(db,"appdata",MAIN_DOC));if(!snap.exists())return[];const data=snap.data(),worker=(data.trabalhadores||[]).find(w=>String(w.nome).trim()===currentWorkerName());if(!worker)return[];return(data.eventos||[]).filter(e=>e.idTrab===worker.id).slice().reverse();}
async function openItemReturn(event){const root=document.querySelector("#modal-root");if(!root)return;const max=Number(event.qtd||0);root.innerHTML=`<div class="modal-overlay"><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h2>Registar devolução</h2><button class="icon-btn" data-close>×</button></div><div class="return-confirm-box"><strong>${esc(event.epi)}${event.tamanho?` · Tam. ${esc(event.tamanho)}`:""}</strong><span class="meta">Entregue em ${esc(event.data||"—")} · Quantidade atualmente entregue: <strong>${max}</strong></span></div><form id="single-return-form" style="margin-top:12px"><div class="field-row"><label class="field-label">Quantidade a devolver</label><input class="input" name="qtd" type="number" min="1" max="${max}" value="1" required></div><div class="field-row"><label class="field-label">O que fazer com o EPI?</label><div class="return-destination"><button type="button" class="ghost-btn return-stock selected" data-destination="stock">↩ Voltar ao stock</button><button type="button" class="ghost-btn return-discard" data-destination="discard">♻ Retirar / inutilizar</button></div><input type="hidden" name="destination" value="stock"><small class="meta" id="return-destination-help">Volta ao armazém associado à entrega${event.armazem?` (${esc(event.armazem)})`:""}.</small></div><div class="field-row"><label class="field-label">Observação (opcional)</label><textarea class="textarea" name="obs" placeholder="Ex.: troca, desgaste, dano, fim de vida…"></textarea></div><button class="primary-btn" type="submit">Confirmar devolução</button></form></div></div>`;root.querySelector("[data-close]").onclick=()=>root.innerHTML="";const form=root.querySelector("#single-return-form"),dest=form.querySelector("[name=destination]"),help=form.querySelector("#return-destination-help");root.querySelectorAll("[data-destination]").forEach(b=>b.onclick=()=>{dest.value=b.dataset.destination;root.querySelectorAll("[data-destination]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");help.textContent=b.dataset.destination==="discard"?"Não volta ao stock. Fica registado como retirado/inutilizado.":`Volta ao armazém associado à entrega${event.armazem?` (${event.armazem})`:""}.`;});form.onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(form);await processReturn(event,Number(fd.get("qtd")||0),String(fd.get("obs")||"").trim(),String(fd.get("destination")||"stock"));};}
async function processReturn(event,qty,obs,destination="stock"){if(!event?.id||qty<=0)return;try{await runTransaction(db,async tx=>{const ref=doc(db,"appdata",MAIN_DOC),snap=await tx.get(ref);if(!snap.exists())throw Error("Dados principais não encontrados.");const data=snap.data(),worker=(data.trabalhadores||[]).find(w=>String(w.nome).trim()===currentWorkerName());if(!worker)throw Error("Trabalhador não encontrado.");const target=(data.eventos||[]).find(e=>String(e.id)===String(event.id)&&e.idTrab===worker.id&&e.tipo==="ENTREGA"&&e.statusAlerta==="ATIVO");if(!target)throw Error("Este EPI já foi devolvido ou alterado. Atualize a ficha e tente novamente.");const available=Number(target.qtd||0);if(qty>available)throw Error(`Só existem ${available} unidade(s) desta entrega para devolver.`);if(!["stock","discard"].includes(destination))throw Error("Destino inválido.");if(destination==="stock")addStock(data,target.armazem||worker.delegacao,target.epi,target.tamanho,qty);if(qty===available){target.statusAlerta="BAIXA";target.estado=destination==="discard"?"Retirado / inutilizado":"Devolvido ao stock";if(obs)target.estado+=` · ${obs}`;}else target.qtd=available-qty;if(!Array.isArray(data.eventos))data.eventos=[];data.eventos.push({id:`DEV-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,idTrab:worker.id,data:todayPT(),tipo:"DEVOLUÇÃO",epi:target.epi,qtd:qty,tamanho:target.tamanho||"",armazem:destination==="stock"?(target.armazem||worker.delegacao):"",destinoDevolucao:destination==="stock"?"STOCK":"INUTILIZADO",estado:destination==="discard"?`Retirado / inutilizado${obs?` · ${obs}`:""}`:`Devolvido ao stock${obs?` · ${obs}`:""}`,statusAlerta:"BAIXA",validade:"",responsavel:"Registo na aplicação"});tx.set(ref,data);});document.querySelector("#modal-root").innerHTML="";const t=document.createElement("div");t.className="success-pop";t.textContent=destination==="discard"?"Devolução registada como inutilizada":"EPI devolvido ao stock e stock atualizado";document.body.appendChild(t);setTimeout(()=>t.remove(),1800);}catch(err){console.error(err);alert(`Não foi possível registar a devolução.\n\n${err.message||err}\n\nNenhum dado foi apagado.`);}}
async function injectPerItemButtons(){const table=document.querySelector(".detail-header")?.parentElement?.querySelector("table");if(!table)return;const rows=Array.from(table.querySelectorAll("tbody tr"));if(!rows.length||rows.some(r=>r.dataset.returnEnhanced==="1"))return;let events;try{events=await getActiveEvents();}catch{return;}rows.forEach((row,index)=>{const event=events[index];if(!event||event.tipo!=="ENTREGA"||event.statusAlerta!=="ATIVO"||Number(event.qtd||0)<=0)return;row.dataset.returnEnhanced="1";const cell=row.insertCell(-1);cell.className="epi-return-cell";cell.innerHTML='<button type="button" class="ghost-btn epi-return-btn" title="Devolver este EPI" aria-label="Devolver este EPI"></button>';cell.querySelector("button").onclick=()=>openItemReturn(event);});}
const removeGlobalReturnButton=()=>document.getElementById("return-epi-btn")?.remove();installStyles();const observer=new MutationObserver(()=>{removeGlobalReturnButton();improveMonthsField();injectPerItemButtons();});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{removeGlobalReturnButton();improveMonthsField();injectPerItemButtons();},500);
