// DPM — Armazém: famílias + entrada por modelo
import { getApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const DOC="dpm_epi_data_v1";
const FAMILIES=["EPI","Equipamento","Ambiente","Portes"];
let busy=false;
const db=()=>getFirestore(getApp());
const ref=()=>doc(db(),"appdata",DOC);
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/\s+/g," ").trim();
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const money=v=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(Number(v||0));
function ensure(d){d=d||{};d.budget ||= {};d.budget.inventoryCatalog ||= {families:{}};d.budget.inventoryCatalog.families ||= {};FAMILIES.forEach(f=>d.budget.inventoryCatalog.families[f] ||= []);d.matriz ||= [];d.warehouses ||= ["DPM Norte","DPM Sul","DPM Algarve"];d.stocks ||= {};d.epiModels ||= {};d.modelStocks ||= {};return d}
async function load(){const s=await getDoc(ref());return ensure(s.exists()?s.data():{})}
async function save(d){await setDoc(ref(),{budget:d.budget,matriz:d.matriz,stocks:d.stocks,epiModels:d.epiModels,modelStocks:d.modelStocks},{merge:true})}
function familyOf(d,name){const families=d.budget.inventoryCatalog.families;for(const f of FAMILIES)if((families[f]||[]).some(x=>norm(x.name)===norm(name)))return f;return d.matriz.some(x=>norm(x.nome)===norm(name))?"EPI":"EPI"}
function modelList(d,epi){return Array.isArray(d.epiModels?.[epi])?d.epiModels[epi].filter(m=>m&&m.ativo!==false):[]}
function mstock(d,w,epi,model){d.modelStocks[w] ||= {};d.modelStocks[w][epi] ||= {};d.modelStocks[w][epi][model] ||= {loose:0,sizes:{}};return d.modelStocks[w][epi][model]}
function legacyStock(d,w,epi){d.stocks[w] ||= {};const r=d.stocks[w][epi];if(typeof r==='number')d.stocks[w][epi]={loose:r,sizes:{}};if(!d.stocks[w][epi]||typeof d.stocks[w][epi]!=="object")d.stocks[w][epi]={loose:0,sizes:{}};d.stocks[w][epi].sizes ||= {};return d.stocks[w][epi]}
function activeArticles(d,f){return d.budget.inventoryCatalog.families[f].filter(x=>x.active!==false)}
function totalLegacy(r){return Number(r.loose||0)+Object.values(r.sizes||{}).reduce((a,b)=>a+Number(b||0),0)}
function totalModel(r){return Number(r.loose||0)+Object.values(r.sizes||{}).reduce((a,b)=>a+Number(b||0),0)}
function injectTabs(d,warehouse){
 const section=[...document.querySelectorAll(".section")].find(s=>s.querySelector(".stock-list"));if(!section)return;
 let tabs=section.querySelector("[data-wh-families]");
 if(!tabs){tabs=document.createElement("div");tabs.dataset.whFamilies="1";tabs.className="family-tabs";tabs.style.cssText="display:flex;gap:8px;overflow-x:auto;padding:4px 0 12px;margin-bottom:8px;position:sticky;top:0;z-index:2;background:var(--bg);";section.querySelector(".field-row")?.insertAdjacentElement("afterend",tabs)}
 const active=tabs.dataset.family||"EPI";tabs.innerHTML=FAMILIES.map(f=>`<button type="button" class="ghost-btn ${f===active?'active':''}" data-wh-family="${f}">${f} <span class="badge blue">${activeArticles(d,f).length}</span></button>`).join("");
 tabs.querySelectorAll("[data-wh-family]").forEach(b=>b.onclick=()=>{tabs.dataset.family=b.dataset.whFamily;renderFamilyStock(d,warehouse,b.dataset.whFamily,section.querySelector('.stock-list'))});
 if(!section.querySelector('.stock-list').dataset.familyRendered){section.querySelector('.stock-list').dataset.familyRendered='1';renderFamilyStock(d,warehouse,active,section.querySelector('.stock-list'))}
}
function renderFamilyStock(d,w,f,list){
 const cats=activeArticles(d,f); if(!cats.length){list.innerHTML='<div class="empty">Não existem artigos ativos nesta família.</div>';return;}
 list.innerHTML=cats.map(a=>stockCard(d,w,f,a.name)).join('');
 list.querySelectorAll('[data-wh-entry]').forEach(b=>b.onclick=()=>openEntry(d,w,b.dataset.whEntry));
}
function stockCard(d,w,f,name){
 const base=d.matriz.find(e=>norm(e.nome)===norm(name));const models=f==='EPI'?modelList(d,name):[];const legacy=legacyStock(d,w,name);const ms=d.modelStocks?.[w]?.[name]||{};let total=0;
 if(models.length){total=models.reduce((s,m)=>s+totalModel(ms[m.nome]||{loose:0,sizes:{}}),0)+totalLegacy(legacy)}else total=totalLegacy(legacy);
 const modelRows=models.map(m=>{const r=ms[m.nome]||{loose:0,sizes:{}};const sizes=Object.entries(r.sizes||{}).filter(([,q])=>Number(q)>0).map(([s,q])=>`${esc(s)}: ${q}`).join(' · ');return `<div class="meta" style="margin-top:4px"><strong>${esc(m.nome)}</strong>${sizes?` · ${sizes}`:''}${r.loose?` · sem tam.: ${r.loose}`:''}</div>`}).join('');
 return `<div class="stock-card"><div><strong>${esc(name)}</strong><div class="risks">${base?`Riscos: ${esc(base.riscos||'')} · ${base.meses||12} meses`:f}</div>${modelRows}<div class="size-list">${!models.length?Object.entries(legacy.sizes||{}).filter(([,q])=>Number(q)>0).map(([s,q])=>`<span>${esc(s)}: ${q}</span>`).join('')|| (legacy.loose?`<span>Sem tamanho: ${legacy.loose}</span>`:''):''}</div></div><div class="stock-actions"><span class="badge ${total>15?'ok':total>5?'warn':'danger'}">Total ${total}</span>${f==='EPI'||f==='Equipamento'?`<button class="ghost-btn" data-wh-entry="${esc(name)}">+ Entrada</button>`:''}</div></div>`
}
function openEntry(d,w,epi){if(busy)return;busy=true;const models=modelList(d,epi);const base=d.matriz.find(e=>norm(e.nome)===norm(epi));const root=document.getElementById('modal-root');const modelOpts=models.length?`<option value="">${models.length>1?'Selecionar modelo':'Modelo'}</option>${models.map((m,i)=>`<option value="${esc(m.id)}">${esc(m.nome)}${m.preco?` · ${money(m.preco)}`:''}</option>`).join('')}`:'<option value="">Sem modelo configurado</option>';root.innerHTML=`<div class="modal-overlay" data-wh-close><div class="modal" role="dialog"><div class="modal-head"><div><h2>Entrada de Stock</h2><p class="meta">${esc(epi)} · ${esc(w)}</p></div><button type="button" class="icon-btn" data-wh-close>×</button></div><form id="wh-entry-form"><div class="field-row"><label>Modelo<select class="select" name="model" ${models.length?'':'disabled'}>${modelOpts}</select></label></div><div class="field-row two"><label>Tamanho<input class="input" name="size" placeholder="Ex.: 42, M, XL"></label><label>Quantidade<input class="input" name="qty" type="number" min="1" value="1" required></label></div><div class="info-box" id="wh-model-info">${models.length?'Escolhe o modelo comprado.':'Este artigo não tem modelos configurados.'}</div><div style="display:flex;justify-content:flex-end;gap:8px"><button type="button" class="ghost-btn" data-wh-close>Cancelar</button><button type="submit" class="primary-btn">Adicionar ao stock</button></div></form></div></div>`;
 const close=()=>{root.innerHTML='';busy=false};root.querySelectorAll('[data-wh-close]').forEach(x=>x.onclick=close);const form=root.querySelector('#wh-entry-form');const sel=form.querySelector('[name=model]');sel?.addEventListener('change',()=>{const m=models.find(x=>x.id===sel.value);root.querySelector('#wh-model-info').textContent=m?`Modelo: ${m.nome}${m.preco?` · ${money(m.preco)}`:''}${Array.isArray(m.tamanhos)&&m.tamanhos.length?` · Tamanhos: ${m.tamanhos.join(', ')}`:''}`:'Escolhe o modelo comprado.'});form.onsubmit=async e=>{e.preventDefault();const model=models.find(x=>x.id===sel?.value);if(models.length&&!model){alert('Seleciona o modelo comprado.');return}const qty=Number(form.qty.value||0),size=String(form.size.value||'').trim().toUpperCase();if(qty<=0){alert('Indica uma quantidade válida.');return}const r=model?mstock(d,w,epi,model.nome):legacyStock(d,w,epi);if(size)r.sizes[size]=Number(r.sizes[size]||0)+qty;else r.loose=Number(r.loose||0)+qty;try{await save(d);close();const sec=[...document.querySelectorAll('.section')].find(s=>s.querySelector('.stock-list'));if(sec)renderFamilyStock(d,w,sec.querySelector('[data-wh-families]')?.dataset.family||'EPI',sec.querySelector('.stock-list'));}catch(err){alert(`Não foi possível adicionar o stock.\n\n${err.message||err}`)}};}
let lastKey='';async function observe(){const app=document.getElementById('app');if(!app)return;const h=app.querySelector('.screen-title h1')?.textContent?.trim();if(h!=='Armazém'){lastKey='';return}const warehouse=app.querySelector('[data-filter="stockWarehouse"]')?.value||'DPM Norte';const key=warehouse+'|'+(app.querySelector('.stock-list')?'1':'0');if(key===lastKey)return;lastKey=key;try{const d=await load();injectTabs(d,warehouse)}catch(e){console.warn('Warehouse UI',e)}}
function start(){new MutationObserver(()=>observe()).observe(document.body,{subtree:true,childList:true});observe();document.addEventListener('click',async e=>{const entry=e.target.closest('[data-entry]');if(!entry)return;const app=document.getElementById('app');if(app?.querySelector('.screen-title h1')?.textContent?.trim()!=='Armazém')return;e.preventDefault();e.stopImmediatePropagation();const w=app.querySelector('[data-filter="stockWarehouse"]')?.value||'DPM Norte';try{const d=await load();openEntry(d,w,entry.dataset.entry)}catch(err){alert(`Não foi possível abrir a entrada de stock.\n\n${err.message||err}`)}},true)}start();
